### ISSUE TITLE
TensorFlow runtime exception

### ISSUE THREAD

**Issue by xsy123xsy** [clausmichele/ViDeNN#16]
when I run this command： **python main_ViDeNN.py --use_gpu=1 --checkpoint_dir=ckpt_videnn --save_dir='./data/denoised' --test_dir='./data'**

I get this **exception**:
**libcublas.so.8.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime**

my environment configuration:
**tensorflow-gpu == 1.4
cuda 11.2
nvidia driver: 460.39  （GTX 1080）**

Traceback:
Traceback (most recent call last):
  File "/home/xiangshouyan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/203.7148.72/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/src/video_denoise_ViDeNN/main_ViDeNN.py", line 8, in <module>
    import tensorflow as tf
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/xiangshouyan/anaconda3/envs/ViDeNN/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/49893582/107228396-98038a80-6a57-11eb-86f6-823d06788c37.png)

**Comment by clausmichele** [comment]
This is not something related to my code, you may have to check the installation of CUDA, CuDNN and related drivers.
You may try to run it on CPU only.

**Comment by xsy123xsy** [comment]
thx. I have fixed this problem by change cuda version from 11.2 to 8.0 and export the lib path using : sudo sh -c "echo '/usr/local/cuda-8.0/lib64' >>  /etc/ld.so.conf.d/cuda.conf"
